apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: docs
  name: docs-prep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: docs-prep
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 35
